name: Prod Pipeline - ECS

on:
  push:
    branches:
      - prod

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: us-east-1

      - name: Login to Amazon ECR
        run: |
          aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin \
          151557938866.dkr.ecr.us-east-1.amazonaws.com

      - name: Build & Push Vote Image
        run: |
          docker build -t vote ./vote
          docker tag vote:latest 151557938866.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:vote-prod-latest
          docker push 151557938866.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:vote-prod-latest

      - name: Build & Push Result Image
        run: |
          docker build -t result ./result
          docker tag result:latest 151557938866.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:result-prod-latest
          docker push 151557938866.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:result-prod-latest

      - name: Build & Push Worker Image
        run: |
          docker build -t worker ./worker
          docker tag worker:latest 151557938866.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:worker-prod-latest
          docker push 151557938866.dkr.ecr.us-east-1.amazonaws.com/lks-voting-image:worker-prod-latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to ECS (Vote)
        run: |
          aws ecs update-service --cluster lks-voting-cluster --service lks-vote-service \
          --force-new-deployment --region us-east-1

      - name: Deploy to ECS (Result)
        run: |
          aws ecs update-service --cluster lks-voting-cluster --service lks-result-service \
          --force-new-deployment --region us-east-1

      - name: Deploy to ECS (Worker)
        run: |
          aws ecs update-service --cluster lks-voting-cluster --service lks-worker-service \
          --force-new-deployment --region us-east-1

      - name: Send SNS Notification
        run: |
          aws sns publish \
          --topic-arn ${{ secrets.AWS_SNS_ARN }} \
          --subject "Deployment Success" \
          --message "Voting App production deployed!"

